"""changed users owner

Revision ID: 98be1d92b0c5
Revises: 780f5f8d4077
Create Date: 2023-10-06 11:12:24.910658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98be1d92b0c5'
down_revision = '780f5f8d4077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
