"""changed attributes

Revision ID: b7f0ad208fcf
Revises: 780f5f8d4077
Create Date: 2023-10-06 11:47:32.832865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f0ad208fcf'
down_revision = '780f5f8d4077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
