"""updated models

Revision ID: fa4281ae2f87
Revises: e4985482d91f
Create Date: 2023-10-03 14:16:58.731278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4281ae2f87'
down_revision = 'e4985482d91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessimgs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessimgs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('businessimgurl', sa.VARCHAR(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
